# Generated by Django 2.1.7 on 2019-03-27 02:28

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import foods.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名')),
                ('order_seq', models.IntegerField(verbose_name='排行')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='foods.Category', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '食物分类',
                'verbose_name_plural': '食物分类',
                'db_table': 't_category',
                'ordering': ['order_seq'],
            },
        ),
    ]
