# Generated by Django 2.1.7 on 2019-03-27 02:41

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion
import foods.models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='食物名称')),
                ('price', models.FloatField(default=1.0, verbose_name='价格')),
                ('step_minute', models.IntegerField(verbose_name='所需时间(分钟)')),
                ('image', models.ImageField(upload_to=foods.models.get_image_name, verbose_name='图片')),
                ('info', DjangoUeditor.models.UEditorField(blank=True, null=True, verbose_name='详情')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Category', verbose_name='分类')),
            ],
            options={
                'verbose_name': '菜谱',
                'verbose_name_plural': '菜谱',
                'db_table': 't_foods',
            },
        ),
    ]
