# Generated by Django 2.1.7 on 2019-03-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QaunActive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateField(auto_now_add=True, verbose_name='发布时间')),
                ('valid_days', models.IntegerField(default=30, verbose_name='有效天数')),
                ('volumns', models.IntegerField(default=10000, verbose_name='限发量')),
                ('title', models.CharField(max_length=200, verbose_name='活动名称')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '优惠劵活动',
                'verbose_name_plural': '优惠劵活动',
                'db_table': 't_quan_active',
                'ordering': ['-publish_date'],
            },
        ),
    ]
